import pandas as pd
#import glob



#funcion para leer los archivos

def lectura_archivos(url):
     
    return pd.read_csv(url)

#funcion para obtner los paises con su codigo desde una pagina web
def obtener_paises_codigo(url):
    tablaASCII =pd.read_html(url)[0]
    df=pd.DataFrame(tablaASCII)
    df_pais=df.iloc[:,0:3]
    df_pais.rename(columns={'Country': 'country_name', 'Alpha-3 code':'country_code'}, inplace='True')
    df_pais['country_name']=df_pais['country_name'].str.upper()
    df_pais.drop(['Alpha-2 code'],axis=1, inplace=True)
    return df_pais     


    """
    * 'AFRICA EASTERN AND SOUTHERN' 
    * 'AFRICA WESTERN AND CENTRAL
    * 'ARAB WORLD'
    * CENTRAL EUROPE AND THE BALTICS 
    * CHANNEL ISLANDS
    * CARIBBEAN SMALL STATES
    'CURACAO':'CURAÇAO'
    * EAST ASIA & PACIFIC (EXCLUDING HIGH INCOME)
    * EARLY-DEMOGRAPHIC DIVIDEND
    * EAST ASIA & PACIFIC
    * EUROPE & CENTRAL ASIA (EXCLUDING HIGH INCOME)
    * EUROPE & CENTRAL ASIA
    'EGYPT, ARAB REP.':'EGYPT'
    * EURO AREA
    * EUROPEAN UNION
    * FRAGILE AND CONFLICT AFFECTED SITUATIONS
    'FAROE ISLANDS':'FAROE ISLANDS (THE)'
    'GAMBIA, THE' :'GAMBIA (THE)'
    * HIGH INCOME
    'HONG KONG SAR, CHINA': 'HONG KONG'
    * HEAVILY INDEBTED POOR COUNTRIES (HIPC)
    * IBRD ONLY}
    * IDA & IBRD TOTAL
    * IDA TOTAL
    * IDA BLEND
    * IDA ONLY
    * NOT CLASSIFIED
    ****IRELAND
    'IRAN, ISLAMIC REP.' :'IRAN (ISLAMIC REPUBLIC OF)'
    ****IRAQ
    'KYRGYZ REPUBLIC' :'KYRGYZSTAN'
    'ST. KITTS AND NEVIS' :'SAINT KITTS AND NEVIS'
    *LATIN AMERICA & CARIBBEAN (EXCLUDING HIGH INCOME)
    'LAO PDR':'LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)'
    * LATIN AMERICA & CARIBBEAN
    * LEAST DEVELOPED COUNTRIES: UN CLASSIFICATION
    LOW INCOME
    * LOWER MIDDLE INCOME
    * LOW & MIDDLE INCOME
    * LATE-DEMOGRAPHIC DIVIDEND
    * MACAO SAR, CHINA
    * ST. MARTIN (FRENCH PART)
    'MOLDOVA':'MOLDOVA (THE REPUBLIC OF)'
    * MIDDLE EAST & NORTH AFRICA
    * MARSHALL ISLANDS:'MARSHALL ISLANDS (THE)'
    * MIDDLE INCOME
    * NORTH MACEDONIA
    * MIDDLE EAST & NORTH AFRICA (EXCLUDING HIGH INCOME)
    'NORTHERN MARIANA ISLANDS' :'NORTHERN MARIANA ISLANDS (THE)'
    * NORTH AMERICA
    'NIGER':'NIGER (THE)' 
    'NETHERLANDS':'NETHERLANDS (THE)'
    * OECD MEMBERS
    * OTHER SMALL STATES
    'PHILIPPINES' : 'PHILIPPINES (THE)'
    * PRE-DEMOGRAPHIC DIVIDEND
    'KOREA, DEM. PEOPLE'S REP.' : 'KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)'
    * WEST BANK AND GAZA
    * PACIFIC ISLAND SMALL STATES
    * POST-DEMOGRAPHIC DIVIDEND
    'RUSSIAN FEDERATION':'RUSSIAN FEDERATION (THE)'
    * SOUTH ASIA
    ****'SUDAN' :'SUDAN (THE)'
    * SUB-SAHARAN AFRICA (EXCLUDING HIGH INCOME)
    * SUB-SAHARAN AFRICA
    * SMALL STATES
    * EAST ASIA & PACIFIC (IDA & IBRD COUNTRIES)
    * EUROPE & CENTRAL ASIA (IDA & IBRD COUNTRIES)
    * LATIN AMERICA & THE CARIBBEAN (IDA & IBRD COUNTRIES)
    * MIDDLE EAST & NORTH AFRICA (IDA & IBRD COUNTRIES)
    * SOUTH ASIA (IDA & IBRD)
    * SUB-SAHARAN AFRICA (IDA & IBRD COUNTRIES)
    ****TUVALU
    'TANZANIA':'TANZANIA, UNITED REPUBLIC OF'
    *****UGANDA
    *UPPER MIDDLE INCOME
    'UNITED STATES':'UNITED STATES OF AMERICA (THE)'
    *WORLD
    ****KOSOVO
    ****'YEMEN, REP.': 'YEMEN'
    ***ZAMBIA"""